### ISSUE TITLE
Crashes on start up on 1.15.1

### ISSUE THREAD

**Issue by Wreckstation** [xxmicloxx/VolumetricShading#5]
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.1 (Stable)7/20/2021 2:28:18 PM: Critical error occurred
System.TypeLoadException: Could not load type 'Vintagestory.API.IAmbientManager' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at VolumetricShading.Effects.DeferredLighting.OnEndRender()
   at VolumetricShading.Effects.DeferredLightingRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _LpTdfLOAWwrFBtCzFbbeuEgj89qb._BdAGMFwyOn5tRjrJ2AiJBfbgDkH(Single )
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._rmjRcUg6ZZy8gFclAtdmfo8RemC(Single )
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._uf2x7pSJniCpFh7nbMvuI5iHIsh(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO , String[] )
   at _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/9/2021 7:31:22 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1193927948737580652, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.0.2.0
P3: 10.0.17763.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\_\AppData\Local\Temp\RDR7333.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7334.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7344.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7362.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7382.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 890addb3-1314-424b-9a59-3c62b39ea9b0
Report Status: 268435456
Hashed bucket: f27315e37f0020aaf091af24c7ea0e6c
Cab Guid: 0 }
```

**Comment by xxmicloxx** [comment]
Fixed by f66b6ecfbfd328d23d43e286ef458d6cc9fe768d. New version can be downloaded from the Mod DB.
